#can be many wiki & many www sites

[server]
port = 3000
addr = "0.0.0.0"

[[wiki]]
name = "wiki"
url = "git@github.com:threefoldfoundation/info_threefold.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = ""

[[blog]]
name = "tfblog"
title = "Threefold Blog"
url = "https://github.com/threefoldfoundation/blog_threefold"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = ""
#environment name (for example:  production, staging, testing)
environment = ""
domain = "blog2.threefold.io"


